import Foundation

enum LocalizedKey: String {
    case appTitle = "app.title"
    case categories = "sidebar.categories"
    case quickPanels = "sidebar.quickPanels"
    case summaryTitle = "detail.summary"
    case actionsTitle = "detail.actions"
    case activityTitle = "inspector.activity"
    case logsTitle = "inspector.logs"
    case settingsTitle = "settings.title"
    case settingsSubtitle = "settings.subtitle"
    case manualRefresh = "toolbar.refresh"
    case openSettings = "toolbar.settings"
    case toggleInspector = "toolbar.inspector"
    case statusCompleted = "status.completed"
    case statusRunning = "status.running"
    case statusAttention = "status.attention"
    case statusCatalog = "status.catalog"
    case statusReset = "status.reset"
    case statusResetMessage = "status.reset.message"
    case statusResetFailedMessage = "status.reset.failedMessage"
    case statusEmpty = "status.empty"
    case statusReady = "status.ready"
    case statusEnabled = "status.enabled"
    case statusFailed = "status.failed"
    case statusNeedsReview = "status.needsReview"
    case run = "action.run"
    case restoreButton = "action.restore"
    case privileged = "action.privileged"
    case intelOnly = "action.intelOnly"
    case intelOnlyHint = "action.intelOnlyHint"
    case requiresRestart = "action.requiresRestart"
    case riskyAction = "action.risky"
    case safeAction = "action.safe"
    case lastRun = "action.lastRun"
    case noData = "common.noData"
    case confirmRiskyTitle = "confirm.title"
    case confirmRiskyMessage = "confirm.message"
    case continueAction = "confirm.continue"
    case cancel = "common.cancel"
    case done = "common.done"
    case englishLanguage = "common.language.english"
    case vietnameseLanguage = "common.language.vietnamese"
    case unavailable = "common.unavailable"
    case generalSection = "settings.general"
    case languageSection = "settings.language.section"
    case refreshSection = "settings.refresh.section"
    case appearanceSection = "settings.appearance.section"
    case safetySection = "settings.safety.section"
    case languageLabel = "settings.language.label"
    case refreshIntervalLabel = "settings.refresh.interval"
    case showInspectorLabel = "settings.inspector.default"
    case confirmPrivilegedLabel = "settings.safety.confirmPrivileged"
    case rowDensityLabel = "settings.density.label"
    case rowDensityComfortable = "settings.density.comfortable"
    case rowDensityCompact = "settings.density.compact"
    case refreshStatusFormat = "settings.refresh.statusFormat"
    case refreshManual = "settings.refresh.manual"
    case refresh5m = "settings.refresh.5m"
    case refresh10m = "settings.refresh.10m"
    case refresh30m = "settings.refresh.30m"
    case refresh60m = "settings.refresh.60m"
    case refreshMinutesFormat = "settings.refresh.minutesFormat"
    case activityFilterLabel = "activity.filter.label"
    case activityFilterHelp = "activity.filter.help"
    case activityFilterAll = "activity.filter.all"
    case activityFilterLast5Minutes = "activity.filter.last5Minutes"
    case activityFilterLastHour = "activity.filter.lastHour"
    case activityFilterToday = "activity.filter.today"
    case storageAvailableSuffix = "system.storage.availableSuffix"
    case systemLabelChip = "system.label.chip"
    case systemLabelCPU = "system.label.cpu"
    case systemLabelMemory = "system.label.memory"
    case systemLabelStorage = "system.label.storage"
    case systemLabelDisplay = "system.label.display"
    case systemLabelBattery = "system.label.battery"
    case systemLabelMacOS = "system.label.macos"
    case panelDashboard = "panel.dashboard"
    case panelAllStatuses = "panel.statuses"
    case panelCPU = "panel.cpu"
    case panelMemory = "panel.memory"
    case panelBattery = "panel.battery"
    case panelMDM = "panel.mdm"
    case metadataEstimate = "metadata.estimate"
    case metadataPrivilege = "metadata.privilege"
    case metadataRestart = "metadata.restart"
    case metadataRisk = "metadata.risk"
    case snapshotCPUCores = "snapshot.cpu.cores"
    case snapshotCPUUsage = "snapshot.cpu.usage"
    case snapshotMemoryFree = "snapshot.memory.free"
    case snapshotMemoryCompressed = "snapshot.memory.compressed"
    case snapshotGPUMetal = "snapshot.gpu.metal"
    case snapshotDiskAvailable = "snapshot.disk.available"
    case snapshotDiskMountPoint = "snapshot.disk.mountPoint"
    case snapshotNetworkGateway = "snapshot.network.gateway"
    case snapshotNetworkHardwarePort = "snapshot.network.hardwarePort"
    case snapshotBatteryPowerSource = "snapshot.battery.powerSource"
    case snapshotBatteryState = "snapshot.battery.state"
    case snapshotBatteryCondition = "snapshot.battery.condition"
    case snapshotBatteryCycleCount = "snapshot.battery.cycleCount"
    case snapshotMDMHostsAdvisory = "snapshot.mdm.hostsAdvisory"
    case snapshotMDMCurrentEnrollment = "snapshot.mdm.currentEnrollment"
    case snapshotMDMADEAssignment = "snapshot.mdm.adeAssignment"
    case snapshotMDMResetRisk = "snapshot.mdm.resetRisk"
    case inspectionToastMessage = "inspection.toast.message"
    case appReadyTitle = "activity.appReady.title"
    case appReadyMessage = "activity.appReady.message"
    case actionCancelledTitle = "activity.actionCancelled.title"
    case actionCancelledMessage = "activity.actionCancelled.message"
    case privilegedPromptTitle = "activity.privilegedPrompt.title"
    case privilegedPromptMessage = "activity.privilegedPrompt.message"
    case privilegedPromptToastTitle = "toast.privilegedPrompt.title"
    case privilegedPromptToastMessage = "toast.privilegedPrompt.message"
    case administratorCancelledTitle = "activity.administratorCancelled.title"
    case administratorCancelledMessage = "activity.administratorCancelled.message"
    case statusRefreshedTitle = "activity.statusRefreshed.title"
    case statusRefreshedMessage = "activity.statusRefreshed.message"
    case runningActionTitle = "activity.runningAction.title"
    case runningActionMessage = "activity.runningAction.message"
    case actionFailedTitle = "activity.actionFailed.title"
    case actionFailedMessage = "activity.actionFailed.message"
    case actionFailedAdministratorMessage = "activity.actionFailedAdministrator.message"
    case actionUnavailableTitle = "activity.actionUnavailable.title"
    case actionUnavailableIntelOnlyMessage = "activity.actionUnavailable.intelOnlyMessage"
    case systemReviewTitle = "system.review.title"
    case systemReviewMessage = "system.review.message"
    case systemReviewStepCount = "system.review.stepCount"
    case systemReviewSelectAll = "system.review.selectAll"
    case systemReviewClearAll = "system.review.clearAll"
    case systemReviewRunSelected = "system.review.runSelected"
    case restoreReviewMessage = "restore.review.message"
    case systemReviewCommandLabel = "system.review.commandLabel"
    case systemReviewAdminBadge = "system.review.adminBadge"
    case systemReviewStepFallbackTitle = "system.review.stepFallback.title"
    case systemReviewStepFallbackDetail = "system.review.stepFallback.detail"
    case statusLoadFailedTitle = "activity.statusLoadFailed.title"
    case statusLoadFailedMessage = "activity.statusLoadFailed.message"
    case actionCompletedWithoutOutput = "logs.noOutputMessage"
    case resultDialogCompletedMessage = "result.dialog.completedMessage"
    case resultDialogInspectionMessage = "result.dialog.inspectionMessage"
    case resultDialogGuidanceMessage = "result.dialog.guidanceMessage"
    case resultDialogFailedMessage = "result.dialog.failedMessage"
    case resultDialogAdministratorCancelledMessage = "result.dialog.administratorCancelledMessage"
    case resultDialogIntelOnlyMessage = "result.dialog.intelOnlyMessage"
    case resultDialogDetailsTitle = "result.dialog.detailsTitle"
    case restoreRunSelected = "restore.review.runSelected"
    case restoreCategoryButton = "restore.category.button"
    case resetDefaultsAllButton = "restore.all.button"
    case restoreActionTitle = "restore.action.title"
    case restoreCategoryTitle = "restore.category.title"
    case resetDefaultsAllTitle = "restore.all.title"
    case restoreSettingTitle = "restore.setting.title"
    case restoreSettingDetail = "restore.setting.detail"
    case restorePowerDefaultsTitle = "restore.powerDefaults.title"
    case restorePowerDefaultsDetail = "restore.powerDefaults.detail"
    case restorePreferenceOverrideTitle = "restore.preferenceOverride.title"
    case restorePreferenceOverrideDetail = "restore.preferenceOverride.detail"
    case restoreFirewallTitle = "restore.firewall.title"
    case restoreFirewallDetail = "restore.firewall.detail"
    case restoreSpotlightTitle = "restore.spotlight.title"
    case restoreSpotlightDetail = "restore.spotlight.detail"
    case restoreTrimTitle = "restore.trim.title"
    case restoreTrimDetail = "restore.trim.detail"
    case restoreAutoBootTitle = "restore.autoboot.title"
    case restoreAutoBootDetail = "restore.autoboot.detail"
    case restoreReloadDockTitle = "restore.reloadDock.title"
    case restoreReloadDockDetail = "restore.reloadDock.detail"
    case restoreStepFallbackTitle = "restore.stepFallback.title"
    case restoreStepFallbackDetail = "restore.stepFallback.detail"
    case restoreRunFirstRequired = "restore.runFirstRequired"
    case restoreActivityTitle = "restore.activity.title"
    case restoreActivityMessage = "restore.activity.message"
    case restoreCompletedMessage = "restore.completed.message"
    case restoreUnavailableTitle = "restore.unavailable.title"
    case restoreUnavailableMessage = "restore.unavailable.message"
    case restoreNothingAvailableMessage = "restore.nothingAvailable.message"
    case restoreAdministratorCancelledMessage = "restore.result.administratorCancelledMessage"
    case restoreAdministratorCancelledDetail = "restore.activity.administratorCancelled.detail"
    case restoreFailedTitle = "restore.failed.title"
    case restoreFailedMessage = "restore.failed.message"
    case restoreFailedDetail = "restore.failed.detail"
    case quitConfirmRunningMessage = "quit.confirm.runningMessage"
    case quitConfirmReviewMessage = "quit.confirm.reviewMessage"
    case quitConfirmPrivilegeMessage = "quit.confirm.privilegeMessage"
    case quitConfirmResultMessage = "quit.confirm.resultMessage"
    case quitConfirmGenericMessage = "quit.confirm.genericMessage"
    case quitConfirmTitle = "quit.confirm.title"
    case quitConfirmClose = "quit.confirm.close"
    case noOptimizationsYet = "logs.noOptimizationsYet"
    case logsConsoleDescription = "logs.consoleDescription"
    case detailSummary = "detail.summary.label"
    case noLogsYet = "inspector.noLogs"
    case noOutputYet = "inspector.noOutput"
    case activityDelete = "activity.delete"
    case activityClearAll = "activity.clearAll"
    case commonYes = "common.yes"
    case commonNo = "common.no"
    case commonOf = "common.of"
    case commonUsed = "common.used"
    case mdmStatusCurrentlyEnrolled = "mdm.status.currentlyEnrolled"
    case mdmStatusNotCurrentlyEnrolled = "mdm.status.notCurrentlyEnrolled"
    case mdmStatusDepAdeAssigned = "mdm.status.depAdeAssigned"
    case mdmStatusHistoricalTracesFound = "mdm.status.historicalTracesFound"
    case mdmStatusNeedsReview = "mdm.status.needsReview"
    case mdmRiskLikelyYes = "mdm.risk.likelyYes"
    case mdmRiskNoClearTrigger = "mdm.risk.noClearTrigger"
    case mdmRiskHistoricalTracesSuggestReview = "mdm.risk.historicalTracesSuggestReview"
    case mdmHostsWarningBypassDetected = "mdm.hosts.warningBypassDetected"
    case mdmHostsNoBypassDetected = "mdm.hosts.noBypassDetected"
    case mdmHostsAdvisoryUnavailable = "mdm.hosts.advisoryUnavailable"
    case batteryConditionNormal = "battery.condition.normal"
    case batteryConditionGood = "battery.condition.good"
    case batteryConditionPoor = "battery.condition.poor"
    case batteryConditionFair = "battery.condition.fair"
    case batteryConditionExcellent = "battery.condition.excellent"
    case batteryPowerSourceAC = "battery.powerSource.ac"
    case batteryPowerSourceBattery = "battery.powerSource.battery"
    case batteryStateCharging = "battery.state.charging"
    case batteryStateDischarging = "battery.state.discharging"
    case batteryStateCharged = "battery.state.charged"
    case cpuSnapshotTitle = "cpu.snapshot.title"
    case cpuSnapshotAutoRefresh = "cpu.snapshot.autoRefresh"
    case cpuSnapshotCollecting = "cpu.snapshot.collecting"
    case cpuSnapshotNotStarted = "cpu.snapshot.notStarted"
    case cpuSnapshotClickToStart = "cpu.snapshot.clickToStart"
    case cpuSnapshotStartMonitoring = "cpu.snapshot.startMonitoring"
    case cpuSnapshotCores = "cpu.snapshot.cores"
    case cpuSnapshotThermal = "cpu.snapshot.thermal"
    case cpuSnapshotOverallUsage = "cpu.snapshot.overallUsage"
    case cpuSnapshotCollectingData = "cpu.snapshot.collectingData"
    case cpuSnapshotClusterActivity = "cpu.snapshot.clusterActivity"
    case cpuSnapshotPerCoreFrequency = "cpu.snapshot.perCoreFrequency"
    case cpuSnapshotCoreResidency = "cpu.snapshot.coreResidency"
    case cpuSnapshotFrequencyDistribution = "cpu.snapshot.frequencyDistribution"
    case cpuSnapshotPowerConsumption = "cpu.snapshot.powerConsumption"
    case memorySnapshotTitle = "memory.snapshot.title"
    case memorySnapshotAutoRefresh = "memory.snapshot.autoRefresh"
    case memorySnapshotCollecting = "memory.snapshot.collecting"
    case memorySnapshotNotStarted = "memory.snapshot.notStarted"
    case memorySnapshotClickToStart = "memory.snapshot.clickToStart"
    case memorySnapshotStartMonitoring = "memory.snapshot.startMonitoring"
    case memorySnapshotPressure = "memory.snapshot.pressure"
    case memorySnapshotPressureNormal = "memory.snapshot.pressure.normal"
    case memorySnapshotPressureElevated = "memory.snapshot.pressure.elevated"
    case memorySnapshotPressureCritical = "memory.snapshot.pressure.critical"
    case memorySnapshotPressureHintNormal = "memory.snapshot.pressure.hint.normal"
    case memorySnapshotPressureHintElevated = "memory.snapshot.pressure.hint.elevated"
    case memorySnapshotPressureHintCritical = "memory.snapshot.pressure.hint.critical"
    case memorySnapshotUsageBreakdown = "memory.snapshot.usageBreakdown"
    case memorySnapshotPhysicalMemory = "memory.snapshot.physicalMemory"
    case memorySnapshotMemoryUsed = "memory.snapshot.memoryUsed"
    case memorySnapshotCachedFiles = "memory.snapshot.cachedFiles"
    case memorySnapshotSwapUsed = "memory.snapshot.swapUsed"
    case memorySnapshotAppMemory = "memory.snapshot.appMemory"
    case memorySnapshotWiredMemory = "memory.snapshot.wiredMemory"
    case memorySnapshotCompressed = "memory.snapshot.compressed"
    case memorySnapshotFreeMemory = "memory.snapshot.freeMemory"
    case batterySnapshotTitle = "battery.snapshot.title"
    case batterySnapshotAutoRefresh = "battery.snapshot.autoRefresh"
    case batterySnapshotCollecting = "battery.snapshot.collecting"
    case batterySnapshotNotStarted = "battery.snapshot.notStarted"
    case batterySnapshotClickToStart = "battery.snapshot.clickToStart"
    case batterySnapshotStartMonitoring = "battery.snapshot.startMonitoring"
    case batterySnapshotLevel = "battery.snapshot.level"
    case batterySnapshotPowerSource = "battery.snapshot.powerSource"
    case batterySnapshotChargingState = "battery.snapshot.chargingState"
    case batterySnapshotHealth = "battery.snapshot.health"
    case batterySnapshotCondition = "battery.snapshot.condition"
    case batterySnapshotCycleCount = "battery.snapshot.cycleCount"
    case batterySnapshotHealthStatus = "battery.snapshot.healthStatus"
    case batterySnapshotCapacityDetails = "battery.snapshot.capacityDetails"
    case batterySnapshotFullChargeCapacity = "battery.snapshot.fullChargeCapacity"
    case batterySnapshotDesignCapacity = "battery.snapshot.designCapacity"
    case batterySnapshotCurrentCharge = "battery.snapshot.currentCharge"
    case batteryConditionServiceBattery = "battery.condition.serviceBattery"
    case batteryConditionReplaceSoon = "battery.condition.replaceSoon"
    case batteryConditionReplaceNow = "battery.condition.replaceNow"
    case batteryStateACAttached = "battery.state.acAttached"
    case batteryStateNotCharging = "battery.state.notCharging"
    case batterySnapshotChargerInfo = "battery.snapshot.chargerInfo"
    case batterySnapshotChargerWattage = "battery.snapshot.chargerWattage"
    case batterySnapshotAdapterName = "battery.snapshot.adapterName"
    case batterySnapshotBatteryDetails = "battery.snapshot.batteryDetails"
    case batterySnapshotTemperature = "battery.snapshot.temperature"
    case batterySnapshotManufactureDate = "battery.snapshot.manufactureDate"
    case batterySnapshotSerialNumber = "battery.snapshot.serialNumber"
    case batterySnapshotLowPowerMode = "battery.snapshot.lowPowerMode"
    case batterySnapshotLowPowerModeEnabled = "battery.snapshot.lowPowerMode.enabled"
    case batterySnapshotLowPowerModeDisabled = "battery.snapshot.lowPowerMode.disabled"
    case mdmSnapshotTitle = "mdm.snapshot.title"
    case mdmSnapshotRefresh = "mdm.snapshot.refresh"
    case mdmSnapshotChecking = "mdm.snapshot.checking"
    case mdmSnapshotNotChecked = "mdm.snapshot.notChecked"
    case mdmSnapshotClickToCheck = "mdm.snapshot.clickToCheck"
    case mdmSnapshotCheckNow = "mdm.snapshot.checkNow"
    case mdmSnapshotEnrollmentStatus = "mdm.snapshot.enrollmentStatus"
    case mdmSnapshotCurrentEnrollment = "mdm.snapshot.currentEnrollment"
    case mdmSnapshotEnrolledViaDEP = "mdm.snapshot.enrolledViaDEP"
    case mdmSnapshotDEPAssignment = "mdm.snapshot.depAssignment"
    case mdmSnapshotAssigned = "mdm.snapshot.assigned"
    case mdmSnapshotNotAssigned = "mdm.snapshot.notAssigned"
    case mdmSnapshotOrganization = "mdm.snapshot.organization"
    case mdmSnapshotMDMServer = "mdm.snapshot.mdmServer"
    case mdmSnapshotNoDEPConfig = "mdm.snapshot.noDEPConfig"
    case mdmSnapshotHistoricalTraces = "mdm.snapshot.historicalTraces"
    case mdmSnapshotDEPTraces = "mdm.snapshot.depTraces"
    case mdmSnapshotMDMTraces = "mdm.snapshot.mdmTraces"
    case mdmSnapshotPresent = "mdm.snapshot.present"
    case mdmSnapshotAbsent = "mdm.snapshot.absent"
    case mdmSnapshotHostsBypass = "mdm.snapshot.hostsBypass"
    case mdmSnapshotDetected = "mdm.snapshot.detected"
    case mdmSnapshotNotDetected = "mdm.snapshot.notDetected"
    case mdmSnapshotDEPConfiguration = "mdm.snapshot.depConfiguration"
    case mdmSnapshotSupervised = "mdm.snapshot.supervised"
    case mdmSnapshotRemovable = "mdm.snapshot.removable"
    case mdmSnapshotMandatory = "mdm.snapshot.mandatory"
    case mdmSnapshotSkipSetup = "mdm.snapshot.skipSetup"
    case mdmSnapshotResetRisk = "mdm.snapshot.resetRisk"
    case mdmSnapshotActivelyManaged = "mdm.snapshot.activelyManaged"
    case mdmSnapshotDEPConfigured = "mdm.snapshot.depConfigured"
    case mdmSnapshotHistoricalActivity = "mdm.snapshot.historicalActivity"
    case mdmSnapshotNoActivity = "mdm.snapshot.noActivity"
    case mdmSnapshotRiskHighDesc = "mdm.snapshot.riskHighDesc"
    case mdmSnapshotRiskMediumDesc = "mdm.snapshot.riskMediumDesc"
    case mdmSnapshotRiskLowDesc = "mdm.snapshot.riskLowDesc"
    case mdmSnapshotRiskUnknownDesc = "mdm.snapshot.riskUnknownDesc"
    case mdmRiskPossible = "mdm.risk.possible"
    case mdmRiskUnlikely = "mdm.risk.unlikely"
}

struct AppLocalizer {
    let language: AppLanguage

    func text(_ key: LocalizedKey) -> String {
        string(key.rawValue)
    }

    func string(_ key: String) -> String {
        NSLocalizedString(
            key,
            tableName: "Localizable",
            bundle: bundle,
            value: key,
            comment: ""
        )
    }

    func format(_ key: LocalizedKey, _ arguments: CVarArg...) -> String {
        String(format: text(key), locale: locale, arguments: arguments)
    }

    func inspectionToastMessage(title: String) -> String {
        format(.inspectionToastMessage, title)
    }

    private var bundle: Bundle {
        guard let path = Bundle.module.path(forResource: language.rawValue, ofType: "lproj"),
              let bundle = Bundle(path: path) else {
            return .module
        }
        return bundle
    }

    private var locale: Locale {
        Locale(identifier: language.rawValue)
    }
}
